version: '3.8'

services:
  backend:
    image: ${DOCKER_HUB_USERNAME}/reagan-backend:latest
    container_name: reagan-backend
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
      - redis
    networks:
      - app-network

  frontend:
    image: ${DOCKER_HUB_USERNAME}/reagan-frontend:latest
    container_name: reagan-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: ${DOCKER_HUB_USERNAME}/reagan-nginx:latest
    container_name: reagan-nginx
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/letsencrypt/live/msg.mjsec.kr:ro
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: reagan-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE:      ${DB_NAME}
      MYSQL_USER:          ${DB_USERNAME}
      MYSQL_PASSWORD:      ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7.0
    container_name: reagan-redis
    restart: always
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
