# .github/workflows/cd.yml
name: CD to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1) 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) GCP 인증
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3) gcloud 설치 및 초기설정
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id:            ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      # 4) Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 5) Backend 이미지 빌드 & Push to GCR
      - name: Build & Push Backend to GCR
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/reagan-backend:${{ github.sha }}"
          docker build -t $IMAGE -f BACK/reagan/dockerfile .
          docker push $IMAGE

      # 6) Frontend 이미지 빌드 & Push to GCR
      - name: Build & Push Frontend to GCR
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/reagan-frontend:${{ github.sha }}"
          docker build -t $IMAGE -f frontend/dockerfile .
          docker push $IMAGE

      # 7) Nginx 이미지 빌드 & Push to GCR
      - name: Build & Push Nginx to GCR
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/reagan-nginx:${{ github.sha }}"
          docker build -t $IMAGE -f nginx/Dockerfile .
          docker push $IMAGE

      # 8) Cloud Run에 배포
      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy reagan-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/reagan-backend:${{ github.sha }} \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy reagan-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/reagan-frontend:${{ github.sha }} \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Nginx to Cloud Run
        run: |
          gcloud run deploy reagan-nginx \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/reagan-nginx:${{ github.sha }} \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
